language: cpp

compiler:
  - gcc
  - clang

before_script:
  - cmake -G "Unix Makefiles"

script:
  - make && make test

notifications:
  recipients:
    - jeffk@jdkoftinoff.com
  email:
    on_success: change
    on_failure: always

os:
  - linux
  - osx

